### ISSUE TITLE
The Android release will force close itself while trying to save

### ISSUE THREAD

**Issue by zestybaby** [WiseClock/localized-pixel-dungeon-gdx#4]
Current code's Android compiled version would cause force close while exiting the game. After WiseClock's investigation it was confirmed to be unable to save files. Here's the error:

> Error writing file: warrior1.dat (External)

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/1131256/5871053/8129a99c-a312-11e4-8137-24bc7ff94e5e.jpg)

**Comment by WiseClock** [comment]
Solved by adding `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
