### ISSUE TITLE
Item description not translated properly.

### ISSUE THREAD

**Issue by WiseClock** [WiseClock/localized-pixel-dungeon-gdx#5]
![1](https://cloud.githubusercontent.com/assets/1351819/5875691/c8c10fa0-a2c4-11e4-8e20-6351f4d350d0.jpg)

Items which use `info` method from `Item` class are well translated.

![2](https://cloud.githubusercontent.com/assets/1351819/5875686/c3abf7e6-a2c4-11e4-8a62-3905592ed62d.jpg)

![3](https://cloud.githubusercontent.com/assets/1351819/5875692/cb007c4c-a2c4-11e4-9ac3-3b161981625f.jpg)

The ones that have their own `info` overridden `Item` class' combine all the texts together and send to `BitmapText`.
For example, in `MeleeWeapon`, we have:

```
public String info() {
    StringBuilder info = new StringBuilder( desc() );

    String quality = levelKnown && level != 0 ? (level > 0 ? MW_TEXT_2 : MW_TEXT_3) : "";
    info.append(PARA);
    info.append( MW_TEXT_0 + name + MW_TEXT_1 + Utils.indefinite( quality ) );
    info.append( MW_TEXT_4 + tier + MW_TEXT_5);

    if (levelKnown) {
        info.append( MW_TEXT_6 + (MIN + (MAX - MIN) / 2) + MW_TEXT_7);
    } else {
        info.append(
                MW_TEXT_10 + (min() + (max() - min()) / 2) + MW_TEXT_7 +
                        MW_TEXT_11 + typicalSTR() + MW_TEXT_12);
        if (typicalSTR() > Dungeon.hero.STR()) {
            info.append(MW_TEXT_13);
        }
    }

...
```

It appends texts to the original description.

**Comment by UnluckyNinja** [comment]
...I don't get it.

**Comment by WiseClock** [comment]
Solved for `MeleeWeapon`, `Ring`, and `Armor`.  Still more to go...

**Comment by WiseClock** [comment]
Solved.
